#!/usr/bin/env perl
# crontab_daily -- Insert counts into the CCNQ CDR database
# Copyright (C) 2010  Stephane Alnet
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
use strict; use warnings;

# Run-as: any user which has access to both provisioning and CDR CouchDB.

use EV;
use AnyEvent;
use CCNQ::AE;
$CCNQ::AE::debug_receive = 1;

use constant PROGRAM_NAME => 'ccnq2_crontab_invoicing';

use CCNQ::Invoicing::Daily;

use Logger::Syslog;

sub run {
  my ($program_name) = @_;
  info("$program_name starting");

  # If using EV, this will drop callback errors into syslog.
  $EV::DIED = sub {
    error("*** EV::DIED: $@");
  };
  $0 = $program_name;

  CCNQ::Invoicing::Daily::run();
}
run(PROGRAM_NAME);
