#!/usr/bin/env perl
# crontab_cdr -- Insert FreeSwitch CDRs into the CCNQ CDR database
# Copyright (C) 2010  Stephane Alnet
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
use strict; use warnings;

# Run-as: freeswitch

use CCNQ::AE;
$CCNQ::AE::debug_receive = 0;

# This script will locate all CDR files created since the last run,
# process them (sending them to the cdr server), then move the processed
# files away.

use CCNQ::B2BUA::Process;

my $do_rating = $ARGV[0] && $ARGV[0] eq '-r';

CCNQ::B2BUA::Process::run($do_rating);
