#!/bin/bash
# Copyright (C) 2009  Stephane Alnet
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This script can be ran at startup time (e.g. from /etc/rc.local)
# to do real-time capture of SIP packets.
# It must be ran as root (which will happen if ran from /etc/rc.local).

# Which interface should we attempt to capture?
INTERFACE=$1

# Size of the capture spool / ring (in 10Mo blocks)
DEFAULT_RING_SIZE=20
# What should we capture?
DEFAULT_FILTER="udp portrange 5060-5299 or udp portrange 15060-15299 or icmp or tcp portrange 5060-5200 or tcp portrange 15060-15200"

# Do not attempt to run if the logging directory does not exist.
[ -d /var/log/traces ] || exit

# Capture 10Mo per file, up to the indicated size
exec /usr/bin/dumpcap \
  -p -i $INTERFACE \
  -b filesize:10000  -b files:${RING_SIZE:-$DEFAULT_RING_SIZE} \
  -w /var/log/traces/$INTERFACE.pcap \
  -f "${FILTER:-$DEFAULT_FILTER}"
