layout: "main"
logger: "file"
template: template_toolkit
session: 'memcached'
memcached_servers: "/var/sock/memcached"
engines:
  template_toolkit:
    PLUGIN_BASE: 'CCNQ::Portal::Template::Plugin'
    TRIM: 1
    ANYCASE: 0
